[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20", "nginx"]

[phases.build]
cmds = [
    "composer install --no-interaction --optimize-autoloader --no-dev",
    "npm install",
    "npm run build",
    "mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache",
    "chmod -R 775 storage bootstrap/cache",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "chmod -R 775 storage bootstrap/cache && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
